import type {
  AppState,
  HandoverRecord,
  Patient,
  StructuredNote,
} from "./types";

export const STATE_VERSION = 1;

export const emptyStructuredNote = (): StructuredNote => ({
  vitals: {
    temperature: "",
    bloodPressure: "",
    pulse: "",
    spo2: "",
    respiratoryRate: "",
  },
  consciousness: "",
  pain: "",
  mealIntake: "",
  fluidIntake: "",
  elimination: "",
  sleep: "",
  infusion: "",
  medication: "",
  treatment: "",
  examination: "",
  doctorOrder: "",
  family: "",
  other: "",
});

/**
 * 架空患者データ。実在の人物・症例とは一切関係ありません。
 */
export const demoPatients: Patient[] = [
  {
    id: "pt-001",
    patientCode: "P-1042",
    name: "佐藤 花子",
    nameKana: "サトウ ハナコ",
    age: 82,
    gender: "female",
    room: "301-A",
    primaryDiagnosis: "誤嚥性肺炎",
    admissionDate: "2026-08-02",
    attendingDoctor: "宮下 医師",
    nurseInCharge: "田中 看護師",
    adl: "車椅子移乗一部介助・歩行器使用で室内歩行可",
    allergies: "ペニシリン系（発疹）",
    codeStatus: "DNAR",
    infectionControl: "標準予防策（食事時の誤嚥注意）",
    fallRisk: "HIGH",
  },
  {
    id: "pt-002",
    patientCode: "P-1078",
    name: "鈴木 一郎",
    nameKana: "スズキ イチロウ",
    age: 76,
    gender: "male",
    room: "302-B",
    primaryDiagnosis: "慢性心不全 急性増悪",
    admissionDate: "2026-08-04",
    attendingDoctor: "大西 医師",
    nurseInCharge: "山本 看護師",
    adl: "室内独歩可・トイレ自立（労作時息切れあり）",
    allergies: "なし",
    codeStatus: "Full Code",
    infectionControl: "標準予防策",
    fallRisk: "MEDIUM",
  },
  {
    id: "pt-003",
    patientCode: "P-1103",
    name: "高橋 美和",
    nameKana: "タカハシ ミワ",
    age: 88,
    gender: "female",
    room: "305-A",
    primaryDiagnosis: "右大腿骨頸部骨折 術後3日目",
    admissionDate: "2026-08-01",
    attendingDoctor: "森 医師",
    nurseInCharge: "田中 看護師",
    adl: "全介助・端座位訓練中（術後リハビリ開始）",
    allergies: "ラテックス（接触皮膚炎）",
    codeStatus: "Full Code",
    infectionControl: "標準予防策（創部管理）",
    fallRisk: "HIGH",
  },
  {
    id: "pt-004",
    patientCode: "P-1120",
    name: "伊藤 健二",
    nameKana: "イトウ ケンジ",
    age: 64,
    gender: "male",
    room: "308-C",
    primaryDiagnosis: "2型糖尿病 血糖コントロール目的",
    admissionDate: "2026-08-05",
    attendingDoctor: "小林 医師",
    nurseInCharge: "佐々木 看護師",
    adl: "自立",
    allergies: "なし",
    codeStatus: "Full Code",
    infectionControl: "標準予防策",
    fallRisk: "LOW",
  },
  {
    id: "pt-005",
    patientCode: "P-1155",
    name: "渡辺 洋子",
    nameKana: "ワタナベ ヨウコ",
    age: 79,
    gender: "female",
    room: "310-A",
    primaryDiagnosis: "左中大脳動脈領域 脳梗塞",
    admissionDate: "2026-07-30",
    attendingDoctor: "青木 医師",
    nurseInCharge: "山本 看護師",
    adl: "右片麻痺・移乗全介助・嚥下訓練中",
    allergies: "造影剤（掻痒感）",
    codeStatus: "Full Code",
    infectionControl: "標準予防策（口腔ケア強化）",
    fallRisk: "HIGH",
  },
  {
    id: "pt-006",
    patientCode: "P-1188",
    name: "中村 誠",
    nameKana: "ナカムラ マコト",
    age: 71,
    gender: "male",
    room: "312-B",
    primaryDiagnosis: "COPD 急性増悪",
    admissionDate: "2026-08-03",
    attendingDoctor: "大西 医師",
    nurseInCharge: "佐々木 看護師",
    adl: "室内歩行自立・入浴一部介助（在宅酸素 1L/分）",
    allergies: "なし",
    codeStatus: "Full Code",
    infectionControl: "飛沫予防策",
    fallRisk: "MEDIUM",
  },
  {
    id: "pt-007",
    patientCode: "P-1201",
    name: "小川 久美",
    nameKana: "オガワ クミ",
    age: 68,
    gender: "female",
    room: "315-A",
    primaryDiagnosis: "腹腔鏡下胆嚢摘出術 術後1日目",
    admissionDate: "2026-08-06",
    attendingDoctor: "森 医師",
    nurseInCharge: "田中 看護師",
    adl: "見守り歩行可（術後疼痛あり）",
    allergies: "なし",
    codeStatus: "Full Code",
    infectionControl: "標準予防策（創部管理）",
    fallRisk: "MEDIUM",
  },
  {
    id: "pt-008",
    patientCode: "P-1233",
    name: "松本 剛",
    nameKana: "マツモト ツヨシ",
    age: 55,
    gender: "male",
    room: "316-C",
    primaryDiagnosis: "急性腎盂腎炎",
    admissionDate: "2026-08-06",
    attendingDoctor: "小林 医師",
    nurseInCharge: "山本 看護師",
    adl: "自立",
    allergies: "なし",
    codeStatus: "Full Code",
    infectionControl: "標準予防策",
    fallRisk: "LOW",
  },
  {
    id: "pt-009",
    patientCode: "P-1245",
    name: "林 里美",
    nameKana: "ハヤシ サトミ",
    age: 47,
    gender: "female",
    room: "317-A",
    primaryDiagnosis: "気管支喘息 発作後",
    admissionDate: "2026-08-05",
    attendingDoctor: "青木 医師",
    nurseInCharge: "佐々木 看護師",
    adl: "自立",
    allergies: "ハウスダスト・アスピリン喘息の既往",
    codeStatus: "Full Code",
    infectionControl: "標準予防策",
    fallRisk: "LOW",
  },
  {
    id: "pt-010",
    patientCode: "P-1260",
    name: "吉田 正夫",
    nameKana: "ヨシダ マサオ",
    age: 84,
    gender: "male",
    room: "318-B",
    primaryDiagnosis: "前立腺肥大症 尿閉",
    admissionDate: "2026-08-04",
    attendingDoctor: "小林 医師",
    nurseInCharge: "田中 看護師",
    adl: "杖歩行自立",
    allergies: "なし",
    codeStatus: "Full Code",
    infectionControl: "標準予防策（膀胱留置カテーテル管理）",
    fallRisk: "MEDIUM",
  },
  {
    id: "pt-011",
    patientCode: "P-1274",
    name: "斉藤 恵",
    nameKana: "サイトウ メグミ",
    age: 59,
    gender: "female",
    room: "319-A",
    primaryDiagnosis: "関節リウマチ 加療目的",
    admissionDate: "2026-08-03",
    attendingDoctor: "森 医師",
    nurseInCharge: "山本 看護師",
    adl: "自立（朝のこわばりあり）",
    allergies: "なし",
    codeStatus: "Full Code",
    infectionControl: "標準予防策（免疫抑制剤使用中）",
    fallRisk: "LOW",
  },
  {
    id: "pt-012",
    patientCode: "P-1290",
    name: "岡田 秀樹",
    nameKana: "オカダ ヒデキ",
    age: 73,
    gender: "male",
    room: "320-C",
    primaryDiagnosis: "胃潰瘍 出血後",
    admissionDate: "2026-08-05",
    attendingDoctor: "宮下 医師",
    nurseInCharge: "佐々木 看護師",
    adl: "室内歩行自立",
    allergies: "なし",
    codeStatus: "Full Code",
    infectionControl: "標準予防策",
    fallRisk: "MEDIUM",
  },
];

/** 一部の患者にはあらかじめ申し送り入力を用意しておく。 */
const seedNotes: Record<
  string,
  { freeText: string; structured: Partial<StructuredNote> }
> = {
  "pt-001": {
    freeText:
      "昨夜38.2℃の発熱あり。カロナール内服後、今朝36.8℃まで解熱。夜間トイレ3回あり、立位時ふらつきあり。朝食5割摂取。右前腕より点滴継続中。喀痰やや粘稠で吸引1回実施。",
    structured: {
      vitals: {
        temperature: "36.8",
        bloodPressure: "118/62",
        pulse: "88",
        spo2: "94",
        respiratoryRate: "20",
      },
      consciousness: "清明（JCS 0）",
      pain: "訴えなし",
      mealIntake: "朝食5割",
      fluidIntake: "経口 400ml / 点滴 500ml",
      elimination: "排尿6回・排便なし（3日目）",
      sleep: "夜間トイレ3回で中断あり",
      infusion: "右前腕 末梢ルート、ソルデム3A 500ml 継続中",
      medication: "カロナール500mg 頓用（22時内服）、抗菌薬 点滴1日2回",
      treatment: "口腔ケア1日3回、体位ドレナージ実施",
      examination: "本日採血・胸部X線予定",
      doctorOrder: "38.0℃以上でカロナール頓用可。SpO2 93%未満で酸素1L開始。",
      family: "長女が夕方面会予定",
      other: "食事はとろみ付き・座位30分保持",
    },
  },
  "pt-003": {
    freeText:
      "術後3日目。夜間、創部痛の訴えあり NRS 7。頓用鎮痛剤使用後 NRS 3まで軽減。離床時に軽度めまいの訴えあり、端座位で経過観察。夜間トイレ介助2回。朝食3割摂取。",
    structured: {
      vitals: {
        temperature: "37.4",
        bloodPressure: "104/58",
        pulse: "96",
        spo2: "96",
        respiratoryRate: "18",
      },
      consciousness: "清明",
      pain: "創部痛 NRS 7 → 鎮痛剤後 NRS 3",
      mealIntake: "朝食3割",
      fluidIntake: "経口 300ml",
      elimination: "排尿4回・排便なし",
      sleep: "疼痛で中途覚醒あり",
      infusion: "左前腕 末梢ルート 生食ロック中",
      medication: "ロキソニン頓用（3時使用）、下剤 眠前",
      treatment: "創部ガーゼ交換、弾性ストッキング着用中",
      examination: "術後採血予定",
      doctorOrder: "離床はリハビリ介入下で。疼痛時は頓用可。",
      family: "息子へ電話連絡済み",
      other: "ベッド柵4点・離床センサー使用中",
    },
  },
  "pt-006": {
    freeText:
      "早朝より喘鳴増強、労作時に息切れの訴えあり。SpO2 room air 91%まで低下し、酸素1L/分開始後 94%へ改善。口すぼめ呼吸の指導実施。痰の喀出は自力で可能。",
    structured: {
      vitals: {
        temperature: "37.1",
        bloodPressure: "138/78",
        pulse: "102",
        spo2: "91",
        respiratoryRate: "26",
      },
      consciousness: "清明",
      pain: "なし",
      mealIntake: "朝食7割",
      fluidIntake: "経口 600ml",
      elimination: "排尿5回・排便1回",
      sleep: "起座呼吸気味で浅い",
      infusion: "なし",
      medication: "吸入薬 1日2回、ステロイド内服中",
      treatment: "酸素1L/分（経鼻カニューレ）開始",
      examination: "血液ガス検査を医師が検討中",
      doctorOrder: "SpO2 88%未満で医師コール。酸素は最大2L/分まで。",
      family: "妻へ状態説明済み",
      other: "禁煙指導継続中",
    },
  },
};

export const createRecord = (patientId: string): HandoverRecord => {
  const seed = seedNotes[patientId];
  return {
    patientId,
    freeText: seed?.freeText ?? "",
    structured: { ...emptyStructuredNote(), ...(seed?.structured ?? {}) },
    result: null,
    status: "pending",
    completedAt: null,
    updatedAt: new Date().toISOString(),
  };
};

/** 申し送り完了済みとして初期表示する患者（ダッシュボードの集計用）。 */
const completedSeed = new Set([
  "pt-002",
  "pt-004",
  "pt-005",
  "pt-008",
  "pt-009",
  "pt-010",
  "pt-011",
  "pt-012",
]);

export const createDemoState = (): AppState => {
  const records: Record<string, HandoverRecord> = {};
  for (const patient of demoPatients) {
    const record = createRecord(patient.id);
    if (completedSeed.has(patient.id)) {
      record.status = "completed";
      record.completedAt = new Date().toISOString();
    }
    records[patient.id] = record;
  }
  return {
    version: STATE_VERSION,
    patients: demoPatients.map((patient) => ({ ...patient })),
    records,
  };
};
